pos(unconnected(8,1)).
pos(unconnected(8,2)).
pos(unconnected(8,3)).
pos(unconnected(8,4)).
pos(unconnected(8,5)).
pos(unconnected(8,6)).
pos(unconnected(8,7)).
pos(unconnected(1,8)).
pos(unconnected(2,8)).
pos(unconnected(3,8)).
pos(unconnected(4,8)).
pos(unconnected(5,8)).
pos(unconnected(6,8)).
pos(unconnected(7,8)).
pos(unconnected(9,8)).
pos(unconnected(8,9)).
neg(unconnected(1,2)).
neg(unconnected(1,3)).
neg(unconnected(1,4)).
neg(unconnected(1,5)).
neg(unconnected(1,6)).
neg(unconnected(1,7)).
neg(unconnected(1,9)).
neg(unconnected(2,1)).
neg(unconnected(2,3)).
neg(unconnected(2,4)).
neg(unconnected(2,5)).
neg(unconnected(2,6)).
neg(unconnected(2,7)).
neg(unconnected(2,9)).
neg(unconnected(3,1)).
neg(unconnected(3,2)).
neg(unconnected(3,4)).
neg(unconnected(3,5)).
neg(unconnected(3,6)).
neg(unconnected(3,7)).
neg(unconnected(3,9)).
neg(unconnected(4,1)).
neg(unconnected(4,2)).
neg(unconnected(4,3)).
neg(unconnected(4,5)).
neg(unconnected(4,6)).
neg(unconnected(4,7)).
neg(unconnected(4,9)).
neg(unconnected(5,1)).
neg(unconnected(5,2)).
neg(unconnected(5,3)).
neg(unconnected(5,4)).
neg(unconnected(5,6)).
neg(unconnected(5,7)).
neg(unconnected(5,9)).
neg(unconnected(6,1)).
neg(unconnected(6,2)).
neg(unconnected(6,3)).
neg(unconnected(6,4)).
neg(unconnected(6,5)).
neg(unconnected(6,7)).
neg(unconnected(6,9)).
neg(unconnected(7,1)).
neg(unconnected(7,2)).
neg(unconnected(7,3)).
neg(unconnected(7,4)).
neg(unconnected(7,5)).
neg(unconnected(7,6)).
neg(unconnected(7,9)).
neg(unconnected(9,1)).
neg(unconnected(9,2)).
neg(unconnected(9,3)).
neg(unconnected(9,4)).
neg(unconnected(9,5)).
neg(unconnected(9,6)).
neg(unconnected(9,7)).
