pos(zendo(0)).
pos(zendo(1)).
pos(zendo(2)).
pos(zendo(3)).
pos(zendo(4)).
pos(zendo(5)).
pos(zendo(6)).
pos(zendo(7)).
pos(zendo(8)).
pos(zendo(9)).
neg(zendo(10)).
neg(zendo(11)).
neg(zendo(12)).
neg(zendo(13)).
neg(zendo(14)).
neg(zendo(15)).
neg(zendo(16)).
neg(zendo(17)).
neg(zendo(18)).
neg(zendo(19)).
